# Exported from Render on 2026-06-07T18:10:06Z
version: "1"
projects:
- name: My project
  environments:
  - name: Production
    services:
    - type: web
      name: Zyronexa
      runtime: python
      repo: https://github.com/Darvispolanco/Zyronexa
      plan: free
      region: oregon
      buildCommand: pip install -r requirements.txt
      startCommand: gunicorn Zyronexa:app
      autoDeployTrigger: "off"
